apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app-deployment
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: my-web-app
  template:
    metadata:
      labels:
        app: my-web-app
    spec:
      containers:
      - name: my-web-app
        image: arundhathitp/project:latest  # Replace with your Docker image name and tag
        ports:
        - containerPort: 80
        - containerPort: 85
